gen_data_dir: "TowerEval-Data-v0.1/data/instructions_data/0_shot"
eval_data_dir: "TowerEval-Data-v0.1/data/raw_data"
gen_output_dir: "TowerEval-Data-v0.1/generations/0_shot"
eval_output_dir: "TowerEval-Data-v0.1/evaluations/0_shot"

tasks: 
  - name: mt
    subtasks:
      flores.en-de:
    metrics:
      chrf:
models:
  - name: deepl_next_gen
    type: deepl
    arguments:
      model: quality_optimized
  - name: deepl_classic
    type: deepl
    arguments:
      model: latency_optimized